spring.application.name=quiz-service

## Change server port
server.port=8081
# MySQL Db connection
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/quizdb
spring.datasource.username=kalirishi
spring.datasource.password=kali@12345

# Spring JPA Hibernate Connection
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
