#spring.application.name=api-gateway
#server.port=8082
#
## Eureka configuration
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
#
## Question Service
#spring.cloud.gateway.routes[0].id=question-service
#spring.cloud.gateway.routes[0].uri=http://localhost:8080
#spring.cloud.gateway.routes[0].predicates[0]=Path=/question/**
#
## Quiz Service
#spring.cloud.gateway.routes[1].id=quiz-service
#spring.cloud.gateway.routes[1].uri=http://localhost:8081
#spring.cloud.gateway.routes[1].predicates[0]=Path=/quiz/**

spring.application.name=api-gateway
server.port=8082

# Eureka configuration
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Question Service
spring.cloud.gateway.server.webflux.routes[0].id=question-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://QUESTION-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/question/**

# Quiz Service
spring.cloud.gateway.server.webflux.routes[1].id=quiz-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://QUIZ-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/quiz/**

